### ISSUE TITLE
Model monitoring

### ISSUE THREAD

**Issue by JanAnders** [mkoehnenlmu/mlops_project_23#17]
Setup some basic monitoring of the model performance over time.
Additionally, it might make sense to monitor the input data for distribution shifts.

**Comment by mkoehnenlmu** [comment]
- [ ] write input and predictions to db
- [ ] set up basic monitoring with evidently
- [ ] add more advanced monitoring
- [ ] move db to google cloud

- [ ] set up alerts in google cloud
- [ ] test alerts
